config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  get 'homes/about' => 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200}
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :post_images, dependent: :destroy
  attachment :user_image
  validates :name, uniqueness: true
  validates :name, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top]
  before_action :correct_user, only: [:edit]

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
      unless @micropost
        redirect_to root_url
      end
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end


  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      @book = Book.new
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @books = Book.all
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :user_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<h1>投稿編集</h1>
<!-- form_with部分 -->
<%= form_with model:@book, local: true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book', class: "btn btn-success" %>
<% end %>

<%= link_to "Show", book_path(@book.id)%>
<p>|</p>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: current_user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <div class="row">
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag book.user, :user_image, :fill, 60, 60, fallback: "noimage.png", size:'100x100' %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: current_user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table">
        <tr>
          <th>
            <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :user_image, :fill, 60, 60, fallback: "noimage.png", size:'100x100' %>
            <% end %>
          </th>
          <th><%= link_to @user.name, user_path(@user.id) %></th>
          <th><%= link_to @book.title, book_path(@book.id) %></th>
          <th><%= @book.body %></th>
          <th><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success edit_book_1834" %></th>
          <th><%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger destroy_book_1834" %></th>
        </tr>
      </table>
      </div>

app/views/homes/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">welcome to <i class="fas fa-book nav-link text-light"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,
      <br>you can share and exchange your opinions, inpressions, and emotions
      <br>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="btn btn-info btn-sm btn-block mb-3 sign_in">
          <%= link_to "Log in", new_user_session_path %>
        </div>
        <div class="btn btn-success btn-sm btn-block sign_up">
          <%= link_to "Sign Up", new_user_registration_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/24be0f817b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                    <%= link_to user_path(current_user) do%>
                      <i class="fas fa-home nav-link text-light">Home</i>
                    <% end %>
                  </i>
                </li>
                <li>
                  <%= link_to users_path do %>
                    <i class="fas fa-users nav-link text-light">Users</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path do %>
                    <i class="fas fa-book-open nav-link text-light">Books</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fas fa-sign-out-alt nav-link text-light">logout</i>
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path do %>
                    <i class="fas fa-home nav-link text-light">Home</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to homes_about_path do %>
                    <i class="fas fa-link nav-link text-light">About</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path do %>
                    <i class="fas fa-user-plus nav-link text-light">sign up</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path do %>
                    <i class="fas fa-sign-in-alt nav-link text-light">login</i>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= notice %>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto"><p>CopyRight Infratop.inc</p></div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :user_image, :fill, 60, 60, fallback: "noimage.png", size:'100x100' %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do%>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book', class: "btn btn-success" %>

<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<h1>User info</h1>
<div class"container">
  <div class="row">
    <%= form_with model:@user, local:true do |f| %>
      <div class="form_group">
        <label for="inputName">Name</label>
        <%= f.text_field:name, autofocus:true, id:"inputName", placeholder:"名前" %>
      </div>
      <div class="form_group">
        <label for="inputImage">Image</label>
        <%= f.attachment_field:user_image, placeholder: "プロフィール画像" %>
      </div>
      <div class="form_group">
        <%= f.text_field:introduction, autofocus:true, id:"inputIntroduction", placeholder:"説明文" %>
      </div>
      <div class="form_group">
        <%= f.submit"Update User", class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: current_user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
      <div class="row">
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= link_to user_path(user.id) do %>
                    <%= attachment_image_tag user, :user_image, :fill, 40, 40, fallback: "noimage.png", size:'100x100' %>
                  <% end %>
                </td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: current_user, book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag @user, :user_image, :fill, 60, 60, fallback: "noimage.png", size:'100x100' %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>